$(function(){
  $("#clickhere1").click(function(){
    $("#p1").fadeToggle();
  });
  $("#clickhere2").click(function(){
    $("#p2").fadeToggle();
  });
  $("#clickhere3").click(function(){
    $("#p3").fadeToggle();
  });
  $("#clickhere4").click(function(){
    $("#p4").fadeToggle();
  });
  $("#clickhere5").click(function(){
    $("#p5").fadeToggle();
  });
  $("#clickhere6").click(function(){
    $("#p6").fadeToggle();
  });
  $("#clickhere7").click(function(){
    $("#p7").fadeToggle();
  });
  $("#clickhere8").click(function(){
    $("#p8").fadeToggle();
  });
  $("#clickhere9").click(function(){
    $("#p9").fadeToggle();
  });
  $("#clickhere10").click(function(){
    $("#p10").fadeToggle();
  });
  $("#clickhere11").click(function(){
    $("#p11").fadeToggle();
  });
  $("#clickhere12").click(function(){
    $("#p12").fadeToggle();
  });
  $("#clickhere13").click(function(){
    $("#p13").fadeToggle();
  });
  $("#clickhere14").click(function(){
    $("#p14").fadeToggle();
  });
  $("#clickhere15").click(function(){
    $("#p15").fadeToggle();
  });
  $("#clickhere16").click(function(){
    $("#p16").fadeToggle();
  });
  $("#clickhere17").click(function(){
    $("#p17").fadeToggle();
  });
  $("#clickhere18").click(function(){
    $("#p18").fadeToggle();
  });
});
